import OpenAI from "openai";
import { GoogleGenAI } from "@google/genai";

// System prompts for quilt-suitable image generation
const DALLE_PROMPT_PREFIX = `Generate images with the artistic vision and expressive style of a professional quilting artist. Each image should be visually striking and emotionally engaging.

CRITICAL REQUIREMENTS:
- Create bold, simplified compositions with clear, defined shapes and edges
- Use a limited color palette (approximately 20-32 distinct colors maximum)
- Avoid fine details, tiny patterns, or intricate textures that cannot be stitched or cut from fabric
- Focus on strong visual impact through color blocks, geometric shapes, and clear boundaries
- Ensure high contrast between adjacent areas for visibility and pattern clarity
- Compositions should be suitable for translation into fabric pieces

User Request: `;

const IMAGEN_PROMPT_PREFIX = `Create an art quilt design with the vision of a professional quilting artist. The image should be visually striking and emotionally engaging.

Requirements:
- Bold, simplified composition with clear shapes and defined edges
- Limited color palette (20-32 distinct colors maximum)
- No fine details or intricate textures - only shapes that can be cut from fabric
- Strong visual impact through color blocks and geometric/organic forms
- High contrast between adjacent areas
- Suitable for translation into fabric pieces

Design concept: `;

type GenerateResult = {
  success: boolean;
  image?: string;
  model?: string;
  error?: string;
};

/**
 * Generate image using OpenAI DALL-E 3
 */
async function generateWithOpenAI(prompt: string): Promise<GenerateResult> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return { success: false, error: "OPENAI_API_KEY not set" };
  }

  try {
    const openai = new OpenAI({ apiKey });
    const fullPrompt = `${DALLE_PROMPT_PREFIX}${prompt}

Execute this as a quilt-suitable design following all requirements above.`;

    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt: fullPrompt,
      n: 1,
      size: "1024x1024",
      quality: "standard",
      response_format: "b64_json",
    });

    const imageData = response.data?.[0]?.b64_json;
    if (!imageData) {
      return { success: false, error: "No image generated by DALL-E" };
    }

    return {
      success: true,
      image: `data:image/png;base64,${imageData}`,
      model: "DALL-E 3",
    };
  } catch (error) {
    console.error("OpenAI error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "OpenAI failed",
    };
  }
}

/**
 * Generate image using Google Imagen 4
 */
async function generateWithImagen(prompt: string): Promise<GenerateResult> {
  const apiKey = process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    return { success: false, error: "GOOGLE_API_KEY not set" };
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const fullPrompt = `${IMAGEN_PROMPT_PREFIX}${prompt}`;

    const response = await ai.models.generateImages({
      model: "imagen-4.0-generate-001",
      prompt: fullPrompt,
      config: {
        numberOfImages: 1,
        aspectRatio: "1:1",
      },
    });

    const generatedImage = response.generatedImages?.[0];
    if (!generatedImage?.image?.imageBytes) {
      return { success: false, error: "No image generated by Imagen" };
    }

    // imageBytes is already base64 encoded
    const base64Data = generatedImage.image.imageBytes;

    return {
      success: true,
      image: `data:image/png;base64,${base64Data}`,
      model: "Imagen 4",
    };
  } catch (error) {
    console.error("Imagen error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Imagen failed",
    };
  }
}

export async function POST(request: Request) {
  try {
    const { prompt, provider } = await request.json();

    if (!prompt || typeof prompt !== "string") {
      return Response.json(
        { error: "Missing or invalid prompt" },
        { status: 400 }
      );
    }

    // If provider is specified, use that one
    if (provider === "openai") {
      const result = await generateWithOpenAI(prompt);
      if (result.success) {
        return Response.json(result);
      }
      return Response.json({ error: result.error }, { status: 500 });
    }

    if (provider === "gemini" || provider === "imagen") {
      const result = await generateWithImagen(prompt);
      if (result.success) {
        return Response.json(result);
      }
      return Response.json({ error: result.error }, { status: 500 });
    }

    // Default: try both in parallel for speed, return first success
    const [openaiResult, imagenResult] = await Promise.all([
      generateWithOpenAI(prompt),
      generateWithImagen(prompt),
    ]);

    // Return OpenAI result if successful
    if (openaiResult.success) {
      return Response.json(openaiResult);
    }

    // Fallback to Imagen
    if (imagenResult.success) {
      return Response.json(imagenResult);
    }

    // Both failed
    return Response.json(
      {
        error: `Both providers failed. OpenAI: ${openaiResult.error}, Imagen: ${imagenResult.error}`,
      },
      { status: 500 }
    );
  } catch (error) {
    console.error("Image generation error:", error);
    return Response.json(
      { error: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    );
  }
}
